### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#47]
Add more logs to reflect the user activity

**Comment by maelstrom0x8** [comment]
@sivaprasadreddy 

I would be interested in working on it. This seems like a great opportunity for me to engage more with open-source projects. Could you please assign this issue to me?

Thanks

**Comment by sivaprasadreddy** [comment]
@maelstrom0x8 Assigning this to you.

* Add logs to capture the key details in every controller methods.
* Make sure we are not logging any sensitive data like passwords.
