### ISSUE TITLE
Investigate JOOQ KeySet pagination

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#53]
Currently, the `LIMIT...OFFSET` based pagination approach is used for displaying posts for a category.  Investigate KeySet based pagination that could improve the performance:
* https://blog.jooq.org/faster-sql-paging-with-jooq-using-the-seek-method/
* https://blog.jooq.org/calculating-pagination-metadata-without-extra-roundtrips-in-sql/

**Comment by varunu28** [comment]
@sivaprasadreddy I will like to take a shot at this. Can you please assign it to me.

**Comment by sivaprasadreddy** [comment]
Closing this for now. If we face performance issue, then we will re-open and look into this.
