### ISSUE TITLE
Improve Email verification template

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#55]
The current email verification template (src/main/resources/templates/email/verify-email.html) is a bare-bones HTML file. Apply some styling to look better.

**Comment by kuldeepsidhu88** [comment]
@sivaprasadreddy I added minimal styling to email template. Let me know if you have any other thoughts.

<img width="1116" alt="image" src="https://github.com/sivaprasadreddy/techbuzz/assets/3798255/0cf71d37-a71b-4703-82a0-1dc74712317a">

<img width="370" alt="image" src="https://github.com/sivaprasadreddy/techbuzz/assets/3798255/05b3f405-2d85-429e-9820-2090eb8b6e9d">
