### ISSUE TITLE
In debug mode application run, not able to see mailhog.

### ISSUE THREAD

**Issue by adityachaudhari** [sivaprasadreddy/techbuzz#62]
Hi Team , @sivaprasadreddy 

I am planning to work on #48  for which i need to create new user in my local debug mode.

I am starting application in debug mode just by executing **TechBuzzApplication**  . It starts the application and allow me to register but email goes for verification, i want to validate that email so that my user 'll be created  but i am not able to get the mailHogger on http://localhost:8025/.

tried to up mailHogger by executing : ./run.sh start_infra  which start it but when i start the application my email verification request does not come to this started mailbox.

Please help to navigate what is missing in my case , while its in debug mode where can i do email verification ? does it goes to same mailHog ? but i am not able to see mailHog up .

Please let me know if you need additional information 

Thanks

**Comment by sivaprasadreddy** [comment]
Running **TechBuzzApplication** won't start the containers (postgres, mailhog) automatically. Instead, you can run **TestTechBuzzApplication**, which is under src/test/java directory. See the README file for more details.

**Comment by sivaprasadreddy** [comment]
I hope this issue is resolved. If not, please re-open.

**Comment by adityachaudhari** [comment]
I was able to resolve by changing below prop
it was like 
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_DATABASE:postgres}I changed it to 
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/${DB_DATABASE:postgres}

Thanks for quick help. This can be closed
