### ISSUE TITLE
Implement View User Profile screen

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#72]
When we click on a User link, we should be able to see the user basic details (name, email), Posts created, Voted posts.
The links to users appears mainly in 2 places:
1. In Post listing page, for every post there will be Created By User link
2. There is current logged in user link in TopNav bar

UI Design:
* User Profile Screen can display information [using Tabs](https://getbootstrap.com/docs/5.3/components/navs-tabs/#tabs). ie, Basic Details, Submitted Posts, Votes

**Comment by a-pavithraa** [comment]
@sivaprasadreddy  I am interested to work on this feature

**Comment by a-pavithraa** [comment]
@sivaprasadreddy 
Created some mock templates for your review
For both the tabs, the upvote/downvote buttons are disabled displaying only the count. Please check whether anything needs to be added.

**Created Posts tab**

![image](https://github.com/sivaprasadreddy/techbuzz/assets/23714753/0db8d363-2c71-4e91-a840-7abfa9047fe5)

**Voted Posts tab**

![image](https://github.com/sivaprasadreddy/techbuzz/assets/23714753/32d75244-cbfc-43ef-a1eb-78186f33a245)

**Comment by sivaprasadreddy** [comment]
@a-pavithraa Mockups look good 👍

**Comment by a-pavithraa** [comment]
@sivaprasadreddy I am done with initial changes. Since we have tabs, I need to save the data in session while switching tabs. Is that fine? I have to do some code clean up and small UI fixes. I will do that and raise a PR.

**Comment by sivaprasadreddy** [comment]
@a-pavithraa  I think the better approach is when user click on a tab (Created Posts, Voted Posts) then we can fetch data for that particular tab and display it instead of fetching all tabs data in one go.

**Comment by a-pavithraa** [comment]
@sivaprasadreddy I first tried that approach but it did not work as expected because of conflicts in hrefs and target properties of tabs in my implementation.. So I went with session. I will try to fix that

**Comment by sivaprasadreddy** [comment]
Completed with https://github.com/sivaprasadreddy/techbuzz/pull/80
