### ISSUE TITLE
Implement a scheduled Job to send Weekly digest of new posts

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#81]
1. Create a Scheduled job to send an email with all the new posts since last week
2. Create a Thymeleaf email template for Posts list

**Comment by a-pavithraa** [comment]
@sivaprasadreddy I would like to work on this issue.

**Comment by a-pavithraa** [comment]
@sivaprasadreddy Please let me know whether I can proceed with the following email template


<img width="1288" alt="Screenshot 2023-06-10 at 10 13 21 PM" src="https://github.com/sivaprasadreddy/techbuzz/assets/23714753/7f93d15d-dc97-4a79-b0c8-c1bc1bc30041">

**Comment by a-pavithraa** [comment]
@sivaprasadreddy Could you please let me know whether this template is fine? I will  try to complete it this weekend

**Comment by sivaprasadreddy** [comment]
@a-pavithraa Yes, this looks good.
