### ISSUE TITLE
Implement Forgot Password feature

### ISSUE THREAD

**Issue by sivaprasadreddy** [sivaprasadreddy/techbuzz#94]
When a user forgot's their password, they should be able to:

1. Click on Forgot Password link in Login/Registration pages
2. Show  Forgot Password form with "email" field.
3. If email not exists show "Account Not Found with this email" error.
4. If email exists, create a reset_token(UUID) and send a link "/reset-password?email=email&token=reset_token"
5. When user clicks on that link, validate whether (email + reset_token) is valid. If valid, then show a form with Password and confirm password fields. Upon submission, update the password and set token column to NULL. If invalid, then show error "Invalid password reset request".

**Comment by a-pavithraa** [comment]
@sivaprasadreddy I am interested to work in this issue

**Comment by a-pavithraa** [comment]
@sivaprasadreddy Create PR for the change

**Comment by sivaprasadreddy** [comment]
Done.
